# -*- coding: utf-8 -*-
"""project lv2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jmwW9ikzNSKVjYD3Kcggr2KtqQWgp5vg

# <center> <b>  XỬ LÝ DỮ LIỆU TRONG PANDAS

## **Xử lý dữ liệu**

#### **1. Import dữ liệu**
"""

# Bước 1 : Load data
# Bước 1.1 Import thư viện pandas vào upload file.
from google.colab import files
import pandas as pd
uploaded = files.upload()

# Bước 1.2 / Tạo ra 1 DataFrame có tên là df chứa thông tin dữ liệu

df = pd.read_csv("bank.csv")

"""#### **2. Xem tổng quan về dữ liệu**

##### 2.1 head() và tail()
"""

# Xem 10 dòng dữ liệu đầu tiên
# SELECT TOP SQL
pd.set_option('display.max_rows', 100)
df.head(10) # Xem 10 dòng dữ liệu đầu tiên ( pd.set_option('display.max_rows', 100))

df.tail(10) # Xem 10 dòng dữ liệu cuối cùng

"""##### 2.2 info()"""

#Xem thông tin tổng quan về bộ dữ liệu
df.info()
# Nhận xét :
# 1 / Dữ liệu có 4521 hàng (index từ 0 đến 4520).
# Có 12 cột:

df.describe()

"""#### **3. Làm sạch dữ liệu**

##### 3.1 Liên quan đến dữ liệu có bị null/empty value hay không
"""

# Bước 2 : Làm xem dữ liệu
df.isnull().sum()

"""##### 3Kiểm tra dữ liệu có duplicated không"""

# Bước 3/ Liên quan đến việc kiểm tra dữ liệu có bị trùng lặp duplicate không.
df.duplicated().sum()

df.rename(columns={'y': 'outcome'}, inplace=True)

df.rename(columns={'poutcome': 'previous_outcome'}, inplace=True)

df

# Hàm biến đổi chuyển đổi giây thành phút
def seconds_to_minutes(seconds):
    return seconds / 60

# Áp dụng hàm biến đổi cho cột 'duration' và tạo cột 'minutes'
df['minutes'] = df['duration'].apply(seconds_to_minutes)

df

# Xuất csv file
df.to_csv('bank_cleaned', index=False)